### ISSUE TITLE
Crash game when loading world

### ISSUE THREAD

**Issue by Goblin1101** [Fusion-Flux/GravityChanger#45]
Gravity API couses game crashing. Minecraft version 1.19.2, gravity api version 0.7.19. World loads correctly when I dont use it.

[crash-2022-10-09_16.25.05-client.txt](https://github.com/Fusion-Flux/Gravity-Api/files/9741193/crash-2022-10-09_16.25.05-client.txt)

**Comment by donington** [comment]
I ran into this issue as well.  Tested it against quilt-loader 1.7.4 and 1.7.5-beta3.

Errors in the crash report and logs indicate a problem with the mixin relating to client.BiomeEffectSoundPlayerMixin.

I was able to get the mod to load without errors by removing the line '"client.BiomeEffectSoundPlayerMixin",' in the gravity_api.mixins.json to disable the troublesome NullPointerException.

Don't have time to actually look deeper right now... but I hope that helps figure out where the problem is!

**Comment by Fusion-Flux** [comment]
seems to be the same as #44

**Comment by Fusion-Flux** [comment]
oh wait
same mixin different bug

**Comment by Fusion-Flux** [comment]
fixed
https://modrinth.com/mod/gravity-api/version/0.7.20%2Bquilt

**Comment by donington** [comment]
Just to follow up - your fix worked on my setup.  0.7.20 ftw, thanks!
